channels:
- conda-forge
dependencies:
- python=3.14.2
- pip<=25.3
- pip:
  - mlflow==3.8.1
  - cloudpickle==3.1.2
  - feature-engine==1.9.3
  - numpy==2.4.1
  - packaging==25.0
  - pandas==2.3.3
  - psutil==7.2.1
  - pyarrow==21.0.0
  - pyyaml==6.0.3
  - scikit-learn==1.8.0
  - scipy==1.17.0
name: mlflow-env
